apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-task-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: trend-container
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 80

